// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc157.DriveTest;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static CANJaguar fourWheelDriveCANJaguar1;
	public static CANJaguar fourWheelDriveCANJaguar2;
	public static CANJaguar fourWheelDriveCANJaguar3;
	public static CANJaguar fourWheelDriveCANJaguar4;
	public static RobotDrive fourWheelDriveDrive4x4;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		try
		{
			fourWheelDriveCANJaguar1 = new CANJaguar(2);
			LiveWindow.addActuator("FourWheelDrive", "CAN Jaguar 2", fourWheelDriveCANJaguar1);
		}
		catch (Exception e)
		{
			System.out.println("JAG 2 not found ");
		}

		try
		{
			fourWheelDriveCANJaguar2 = new CANJaguar(5);
			LiveWindow.addActuator("FourWheelDrive", "CAN Jaguar 5", fourWheelDriveCANJaguar2);
		}
		catch (Exception e)
		{
			System.out.println("JAG 5 not found ");
		}

		try
		{
			fourWheelDriveCANJaguar3 = new CANJaguar(6);
			LiveWindow.addActuator("FourWheelDrive", "CAN Jaguar 6", fourWheelDriveCANJaguar3);
		}
		catch (Exception e)
		{
			System.out.println("JAG 6 not found ");
		}

		try
		{
			fourWheelDriveCANJaguar4 = new CANJaguar(7);
			LiveWindow.addActuator("FourWheelDrive", "CAN Jaguar 7", fourWheelDriveCANJaguar4);
		}
		catch (Exception e)
		{
			System.out.println("JAG 7 not found ");
		}

//        fourWheelDriveDrive4x4 = new RobotDrive(fourWheelDriveCANJaguar1, fourWheelDriveCANJaguar2,
//              fourWheelDriveCANJaguar3, fourWheelDriveCANJaguar4);

        fourWheelDriveDrive4x4 = new RobotDrive(fourWheelDriveCANJaguar3, fourWheelDriveCANJaguar3,
                fourWheelDriveCANJaguar3, fourWheelDriveCANJaguar3);
        
        fourWheelDriveDrive4x4.setSafetyEnabled(true);
        fourWheelDriveDrive4x4.setExpiration(0.1);
        fourWheelDriveDrive4x4.setSensitivity(0.5);
        fourWheelDriveDrive4x4.setMaxOutput(1.0);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        System.out.println("Robot init() complete!");
    }
}
